const { firebase, firestore } = require('firebase-admin');

module.exports = {
  regions: {
    jerusalem: {
      counter: 392,
    },
  },
  totalCounter: 3029,
  locations: {
    balfur: {
      id: 'balfur',
      name: 'כיכר פריז',
      city: 'ירושלים',
      counter: 1213,
      latitude: 31.774979,
      longitude: 35.217181,
      recentPictures: [
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '1122',
          likeCounter: 0,
          locationName: 'כיכר פריז',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '5566',
          likeCounter: 0,
          locationName: 'כיכר פריז',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '3344',
          likeCounter: 0,
          locationName: 'כיכר פריז',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
    'rabin-square': {
      id: 'rabin-square',
      name: 'כיכר רבין',
      city: 'תל אביב',
      counter: 689,
      latitude: 32.080485,
      longitude: 34.78062,
      recentPictures: [
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '1122',
          likeCounter: 0,
          locationName: 'כיכר רבין',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '34',
          likeCounter: 0,
          locationName: 'כיכר רבין',
          locationId: 'rabin-square',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
        {
          archived: false,
          authorId: 'd8GSM5GdfuW0KDlH7dy8oqd5ngz1',
          id: '12',
          likeCounter: 0,
          locationName: 'כיכר פריז',
          locationId: 'rabin-square',
          pictureHeight: 1440,
          pictureUrl:
            'https://media.reshet.tv/image/upload/t_main_image_article,f_auto,q_auto/v1596087348/protst1_j79xag.png',
          pictureWidth: 1920,
          text: '',
          type: 'picture',
          coordinates: new firestore.GeoPoint(31.775077, 35.217622),
          createdAt: Date.now(),
          updatedAt: Date.now(),
        },
      ],
    },
    'habima-square': {
      id: 'habima-square',
      name: 'כיכר הבימה',
      city: 'תל אביב',
      counter: 132,
      latitude: 32.072387,
      longitude: 34.7817674,
    },
    'kakal-intersection-tlv': {
      id: 'kakal-intersection-tlv',
      name: 'מחלף קק"ל',
      city: 'תל אביב',
      counter: 27,
      latitude: 32.11904,
      longitude: 34.81236,
    },
    'pardesiya-junction': {
      id: 'pardesiya-junction',
      name: 'צומת פרדסיה',
      city: 'פרדסיה',
      counter: 16,
      latitude: 32.3046,
      longitude: 34.90078,
    },
    'chemed-intersection': {
      id: 'chemed-intersection',
      name: 'מחלף חמד',
      city: 'ירושלים',
      counter: 39,
      latitude: 31.80008,
      longitude: 35.12347,
    },
  },
};
